<div align="center" style="color: #000099"> <h1><b>Climate Change Belief Analysis 2022</b></h1>
    <h4> By </h4>
    <h2>Datafluent Inc.</h2>
</div>

## About Datafluent Inc.
In this era of `Information Technology (IT)`, the variety and quantity of data generated on a daily basis is unprecedented. Data, which is sometimes referred to as the new oil, holds invaluable insights that can make the world a better place and businesses with growth mindsets have started exploiting this invaluable resource to keep thriving in the business world.

Behold **`Datafluent Inc.!`** We are an organisation that enjoys squeezing out every bit of actionable insights from a variety of raw facts and communicating such insights in digestible chunks to our stakeholders. We are a team of five seasoned professionals that excelled in various disciplines. 

## Meet the Team

<div align="center" style="width: 900px; font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://github.com/okonp07/Team-jm3-Advanced-Classification-Base-Notebook/blob/main/The%20team.JPG"
     alt = "The team"
     style="float: center; padding-bottom=0.5em"
     width=900px/>
</div>

## Project Overview
Industrialization is the enabler of modern economic growth and development. However, this comes at the cost of emitting greenhouse gases that contribute, negatively, to climate change and ultimately global warming. Governments, eco-conscious organizations, and civil societies around the world are constantly exploring ways to reduce their carbon footprints. Despite many indices pointing towards climate change, many people are of the belief that climate change is a hoax. Datafluent Inc. is a corporate entity that specializes in mining out actionable insights from raw facts. In this project, we are contracted to use the novel tweets of some individuals to build various Machine Learning (ML) models to identify their beliefs about climate change. These models will be evaluated using the metrics: ***`accuracy, precision, recall, and F1-scores`*** to choose the optimal model. The optimal model’s outcome will help our client to predict how their eco-friendly products will be received by their prospective customers and thus enable them to make strategic business decisions.

## Table of Contents
<a href=#one>1.0 Introduction</a>
- <a href=#1.1>1.1 Project Overview</a>
- <a href=#1.2>1.2 Installing Dependencies and Importing Packages</a>
- <a href=#1.3>1.3 Loading the Data</a>

<a href=#two>2.0 Exploratory Data analysis</a>
- <a href=#2.1>2.1 Data Wrangling</a>

<a href=#three>3.0 Model Building and Evaluations</a>
- <a href=#3.1>3.1 Train-test Split</a>
- <a href=#3.2>3.2 Feature Selection</a>
- <a href=#3.3>3.3 Model Building</a>
- <a href=#3.4>3.4 Model Evaluation and Performance</a>
- <a href=#3.5>3.5 Parameter Tunings</a>

<a href=#four>4.0 Conclusion</a>

<a href=#five>5.0 Submission</a>

<a href=#six>References</a>

<a id="one"></a>

<a id="one"></a>
# 1.0 Introduction
Climate change is a big issue that needs serious attention and many eco-conscious organisations are exploring ways to build eco-friendly products. However, the populace is divided in their beliefs about climate change. **`Datafluent Inc.`** was hired by one such eco-conscious company to build a solution that determines the proportion of the population that believes in climate change. The information that the solution extracts will serve as a basis for the organisation strategic decision-making in building eco-friendly products. In this section, we are going to set the stage for our project on climate change belief analysis of about 16,000 tweets of some individuals. We will also explore the `Machine Learning (ML) tools` we will use in building the sentiment analysis model.

## 1.1 Global Climate Change
Global climate change refers to the average long-term change of climatic conditions over the entire earth. These include warming temperatures and changes in the precipitation as well as the effects of earth's warming such as:

* rising sea levels
* shrinking mountain glaciers
* ice melting at a faster rate than usual in Greenland and Artic
* wildfires
* floods
* droughts
* famine
* increasing desertification etc.

There is a consensus in the scientific community that the earth has been getting warmer in the recent past and this has been linked to human activities, particularly the use of fossil fuels. The dangers of climate change spark debate among people, as we will see when exploring the tweets.  

Earth’s climate has constantly been changing, even long before humans came into the picture. However, scientists have observed unusual changes recently. For example, Earth’s average temperature has been increasing much more quickly than they would expect over the past 150 years as shown in figure 1.1 below. According to scientists, the main human activities that contribute to climate change over the last century are the burning of fossil fuels like coal and oil as well as carbon pollution, which has increased the concentration of atmospheric carbon dioxide(CO2), which is a known greenhouse gas.
<hr>
<div align="center" style="width: 500px; font-size: 80%; text-align: center; margin: 0 auto">
<img src="World_Climate_Change_Chart.png"
     alt="Dummy image 1"
     style="float: center; padding-bottom=0.5em"
     width=900px/>|
    <div align="center">Figure 1.1: World Climate Change Chart</div>
 </div>

## 1.2 Sentiment Analysis
Sentiment analysis is a way of using natural language processing (NLP) and ML tools in identifying opinions expressed in texts. These opinions can be classified as positive (scored as 1), negative (scored as -1), or neutral (scored as 0). Sentiment analysis is important to businesses because it can reveal insights that can be used in improving sales, customer retention, timely problem identification, evaluating customers’ product perceptions, and exploring business opportunities.

In this regard, people can be classified into three based on their perceptions about the causes of climate change. Thus,
1. Pro-sentiment class: they believe that humans contribute to climate change
2. Anti-sentiment class: these are those who do not believe in climate change and those that don’t believe that humans contribute to climate change
3. Neutral class: these are those who take a neutral stand on the matter, displaying no strong positive or negative sentiment.

### *1.2.1 Techniques of sentiment analysis*
Sentiment analysis can be realized in two ways: rule-based and ML sentiment analysis. In rule-based analysis, manual NLP rules like lexicons (lists of words), stemming, tokenization, and parsing are used to simplify complex texts for computers to easily decipher opinions. Whereas, in ML sentiment analysis classification techniques like Naive Bayes, Logistic Regression, Support Vector Machines, Linear Regression, and Deep Learning are used to classify the contextual opinions.

Quality insights are key to data-driven decision-making. At **`Datafluent Inc.`** we strongly believe in extracting only quality insights. Thus, we are going to analyze the given dataset thoroughly using both rule-based and ML techniques of sentiment analysis. This will ensure that no insight is left unturned in informing the decision-making process of our **`esteemed clients.`**

## 1.3 Classification Techniques
We are going to explore the dataset using the following models, compare them and choose the best amongst them.
- Decision Tree Classifier
- Random Forest Classifier
- Linear Support Vector Classifier (LinearSVC)
- Support Vector Classifier (SVC)
- Logistic Regression
- Stochastic Gradient Descent (SGD)

### *1.3.1 Decision tree classifier*
Decision Trees (DTs) are non-parametric supervised learning methods used for classification and regression. Decision trees learn from data to approximate a sine curve with a set of if-then-else decision rules as illustrated in figure 1.2 below. The deeper the tree, the more complex the decision rules, and the fitter the model.

<div align="center" style="width: 500px; font-size: 80%; text-align: center; margin: 0 auto">
<img src="http://www.wordtemplatesdocs.org/wp-content/uploads/2017/11/Decision-Tree-template-free-00004.jpg"
     alt="Decision Tree"
     style="float: center; padding-bottom=0.5em"
     width=900px/>
    <div align="center">Figure 1.2: Decision Tree</div>
 </div>

A decision tree builds classification or regression models in the form of a tree structure. It breaks down data by partitioning it into subsets after each decision while at the same time an associated decision tree is incrementally developed. The final result is a tree with decision nodes and leaf nodes. A decision node has two or more branches. A leaf node represents a classification or decision. The topmost decision node in a tree that corresponds to the best predictor is called the root node. Decision trees can handle both categorical and numerical data.

Decision trees are prone to overfitting. Overfitting happens when the learning algorithm continues to develop hypotheses that reduce training set error at the cost of an increased test set error; One method to tackle overfitting in decision trees is by pruning. 

There are several approaches used to avoid overfitting in building decision trees namely,
- Pre-pruning stops growing the tree earlier, before it perfectly classifies the training set.
- Post-pruning allows the tree to perfectly classify the training set, and then post-prune the tree. 
Practically, the second approach of post-pruning overfits trees is more successful because it is not easy to precisely estimate when to stop growing the tree.

Decision Trees are building blocks for the next machine learning method we will look into, which is the Random Forest Classifier

### *1.3.2 Random Forest Classifier*
Random forest classifier is a Supervised Machine Learning Algorithm that is used widely in classification problems. It builds decision trees on different samples and takes their majority vote for classification. It is said that the more trees it has, the more robust a forest is. Unlike decision trees Random Forest prevents overfitting by creating trees on random subsets .

The Random Forest algorithm works in four steps as follows:
1. select a number of random samples from a given dataset
2. construct a decision tree for each sample and get a prediction result from each decision tree
3. perform a vote for each predicted result
4. select the prediction result with the most votes as the final prediction.

Random Forest Classifier is illustrated in figure 1.3 below:

<div align="center" style="width: 500px; font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://www.freecodecamp.org/news/content/images/2020/08/how-random-forest-classifier-work.PNG"
     alt="Decision Tree"
     style="float: center; padding-bottom=0.5em"
     width=900px/>
    <div align="center">Figure 1.3: Random Forest Classifier</div>
 </div>

### *1.3.3 Support Vector Machine (SVM)*
Support Vector Machine (SVM) is a linear model that can be used for classification problems. The objective of a Linear SVC (Support Vector Classifier) is to fit to the data you provide, returning a "best fit" hyperplane that divides, or categorizes, your data. After getting the hyperplane, you can then feed some features to your classifier to see what the "predicted" class is. It can solve linear and non-linear problems and works well for many practical problems. The idea of SVM is simple: The algorithm creates a line or a hyperplane which separates the data into classes as seen in the figure 1.4 below:


<div align="center" style="width: 500px; font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://pythonmachinelearning.pro/wp-content/uploads/2017/10/SVM-RBF-Iris.png"
     alt="Decision Tree"
     style="float: center; padding-bottom=0.5em"
     width=900px/>
    <div align="center">Figure 1.4: Support Vector Machine</div>
 </div>
 
In the above example, the data is classified into categories that are represented by the blue, white and red class in line with pre-determined conditions stipulated by the SVM algorithm once that is completed, the data is sorted into classes as the final output.

# Context of the Problem

    
Sentiment analysis refers to the use of natural language processing, text analysis, computational linguistics, and biometrics to systematically identify, extract, quantify, and study affective states and subjective information.
 |
![twitter-bird-animated-logo.gif?w=300&zoom=2](https://dropnerblog.files.wordpress.com/2019/12/twitter-bird-animated-logo.gif?w=300&zoom=2)
    
## Context of the Problem
Companies are constructed around lessening one's environmental impact or carbon footprint. They offer products and services that are environmentally friendly and sustainable, in line with their values and ideals. They would like to determine how people perceive climate change and whether or not they believe it is a real threat. Before a company begins to develop products for a segment of the population that believes in climate change and the effects of climate change on the environment and world, it is logical for such a company to first establish the existence of such demography. Even when it is clear that a section of the population indeed believes that there is a threat of environmental change, we must assess such factors as how much of a threat they believe climate change is. How far they may be willing to go to protect the environment and how passionate they are about supporting the efforts of others to fight climate change.

In this experiment, we aim to explore machine learning as a method to assist us in identifying whether or not a person believes in climate change and ascertain if such a person could be converted to a new customer based on their tweets. We will develop ML models that are capable of classifying tweets leaning positively towards a belief that Climate change is a problem and hence desirous of proferring a solution to this problem or leaning negatively towards that belief, hence treating climatic change as no threat. To produce these models, we must first select an appropriate set of data for training that has been annotated. Then, we pre-process and clean these data, to enable us to generate a feature and target set from them. We will then select relevant ML models, on which to train these datasets and evaluate their performance. Model evaluation is done by comparing model predictions against data that have been annotated but not used for training. Once a satisfactory performance of the model has been achieved, we interpret the patterns learned and apply them for further decision-making in the context of the experiment.

<div align="center" style="width: 950px; font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://www.itu.int/en/mediacentre/backgrounders/PublishingImages/climate-change-backgrounder.jpg"
     alt="Dummy image 1"
     style="float: center; padding-bottom=0.5em"
     width=950px/>
    </div>

    ### Problem Statement
    Create a Natural Language Processing model to classify whether or not a person believes in climate change, based on their novel tweet data.
    
    ## Comet ML as a tool for Data Science
   <a id="comet"></a>
# Comet ML as a tool for Data Science
<img src="https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2021/11/cometml.png" width="1000" alt="Drawing" style="width: 1000px;"/>
We will be using Comet to facilitate the model building process as well as a form of version control throughout the development of our model. To begin, we will first install the dependency that allows comet ML to integrate with our notebook and log all changes in our ML model as independent experiments in our comet account. This will allow us to have different versions of our model and will be really helpful in assessing the different properties and functionality of our model versions. This process is done in 3 distinct phases, Pip installation, importation of the experiment, and linking our notebook with our comet account. These processes are completed in the next three cells.

<a id="1.12"></a>
# 2.0 Preprocessing and Exploratory Data Analysis (EDA)
In this section, we are going to build and evaluate several ML models and select the best amongst them.
## 2.1 Installing Dependencies and Importing Packages
In order to successfully build the models, there is a need to pip install some dependencies. Thus, we install the *autotime library, Comet, imblearn, and nltk.*

In [1]:
# install comet
!pip install comet_ml

# importing experiment from Comet
from comet_ml import Experiment

In [ ]:
nltk.download('omw-1.4')

In [2]:
# Link your current workspace and create an experiment in comet with our api key:
experiment = Experiment(
    api_key="9smvwfgsHqWuSsKKueLCtsiBz",
    project_name="global-warming-climate-change-sentiment-analysis-team-jm3",
    workspace="okonp07",
)


COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/okonp07/global-warming-climate-change-sentiment-analysis-team-jm3/d5994fe4c25e4654b15e4f106f028d06



In [3]:
# installations
!pip install parfit
!pip install scikit-plot
!pip install contractions
!pip install -U textblob
!pip install pillow

  Created wheel for parfit: filename=parfit-0.220-py3-none-any.whl size=8658 sha256=c127212c6b43229068dea5ea99a47d464b70f6a2a0aefde953a78220d1bea852
  Stored in directory: c:\users\buhari shehu\appdata\local\pip\cache\wheels\21\0b\03\e9b81c9b318b5efa768bdf01c3aae5438a166d31f444bd800a
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=c47cdcc31f8729654696a7032055a26633f59cc161e524c344919178fb8fb17a
  Stored in directory: c:\users\buhari shehu\appdata\local\pip\cache\wheels\e4\7b\98\b6466d71b8d738a0c547008b9eb39bf8676d1ff6ca4b22af1c
Successfully built parfit sklearn


In [1]:
# imports for Natural Language  Processing
import pandas as pd
import numpy as np
import nltk
import string
import re
from sklearn.pipeline import Pipeline
import pickle

# imports for feature extractioin
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# imports for preprocessing
import contractions
from collections import Counter
from nltk.corpus import wordnet
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.tokenize import TweetTokenizer
from sklearn.preprocessing import label_binarize
from sklearn.model_selection import train_test_split
from nltk.probability import FreqDist
#from wordcloud import WordCloud, ImageColorGenerator
from PIL import Image
from textblob import TextBlob

# imports for classification models
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# imports for hyperparameter tunning
import parfit.parfit as pf
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ParameterGrid

# imports for metrics
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# imports for data visualisation
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt
from sklearn.metrics import plot_roc_curve
from scikitplot.metrics import plot_roc, plot_confusion_matrix
%matplotlib inline

In [5]:
pip install wordcloud

  Using cached wordcloud-1.8.1.tar.gz (220 kB)
  Running setup.py clean for wordcloud
Failed to build wordcloud
    Running setup.py install for wordcloud: started
    Running setup.py install for wordcloud: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.


  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Buhari Shehu\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Buhari Shehu\\AppData\\Local\\Temp\\pip-install-6g8r9q03\\wordcloud_9189f986a54649bda98b703b2db9a210\\setup.py'"'"'; __file__='"'"'C:\\Users\\Buhari Shehu\\AppData\\Local\\Temp\\pip-install-6g8r9q03\\wordcloud_9189f986a54649bda98b703b2db9a210\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Buhari Shehu\AppData\Local\Temp\pip-wheel-_jpk5u4q'
       cwd: C:\Users\Buhari Shehu\AppData\Local\Temp\pip-install-6g8r9q03\wordcloud_9189f986a54649bda98b703b2db9a210\
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build

### 2.2.1 Load and view the data
In this section, we are going to load the test and train datasets and view a snapshot of them to verify they are loaded correctly. We will also copy the datasets so that we can revert back to them in case of problems.

In [3]:
# importing the train & test datasets
train = pd.read_csv('train.csv')
test = pd.read_csv('test_with_no_labels.csv')

# create copies for modelling
train_df = train.copy()
test_df = test.copy()

In [4]:
# check to be sure that the train data was properly imported as a pandas dataframe
train_df.head()

sentiment                                            message  tweetid
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221
1          1  It's not like we lack evidence of anthropogeni...   126103
2          2  RT @RawStory: Researchers say we have three ye...   698562
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954

In [5]:
# check to be sure that the test data was properly imported as a pandas dataframe
test.head()

message  tweetid
0  Europe will now be looking to China to make su...   169760
1  Combine this with the polling of staffers re c...    35326
2  The scary, unimpeachable evidence that climate...   224985
3  @Karoli @morgfair @OsborneInk @dailykos \nPuti...   476263
4  RT @FakeWillMoore: 'Female orgasms cause globa...   872928

**Checking the shape of the dataset**

The shape of the data tells you the number of rows and columns that exists in a particular dataframe. In the next cell, we will examine the number of rows and columns present in the train and test data.

In [6]:
# check the number of rows and columns in the datasets
train_df.shape, test_df.shape

((15819, 3), (10546, 2))

In the next two cells, we will check the proportion of the entire dataset that is commited to the train and test set. We can establish this by checking the percentage of the entire data that is reserved as the train data and the proportion that is reserved as the test data.

In [7]:
# Check the percentage of the data committed as the train set
((15819)/(15819+10546)) * 100

60.0

In [8]:
# Check the percentage of the data committed as the test set
((10546)/(15819+10546)) * 100

40.0

The train data sets shape shows that there are 15819 rows and 3 columns in the train data. The columns are identified as `sentiment`, `message`, and `tweetid`. The test data has 10,546 rows and 2 columns. The columns in the test data set are identified as `message` and `tweetid`. The target (that is the variable that our model seeks to predict) can therefore be identified as the `Sentiment` value. This is why it is only present in the train set. In the course of the development of our model, we will use the "message" and the "tweetid" columns to engineer the features that will be used to predict the `Sentiment` of every tweet in the test data set.

### 2.2.2 Data Preprocessing
Usually, when data is collected in the real world, it comes with a lot of "impurities". Some data would come in formats that are different from the format that the data scientist desires, there may be null values, unrecognizable characters present in the data, etc. Data pre-processing refers to the process of removing these impurities from the data and taking the necessary steps to ensure that the data is in a state that will give clear and interpretable insights and also at its best to be used for the process of ML models. The process of Data pre-processing involves searching for these possible errors in your data and fixing them. 

In [10]:
# cheching if there are missing values in the train dataset
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15819 entries, 0 to 15818
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   sentiment  15819 non-null  int64 
 1   message    15819 non-null  object
 2   tweetid    15819 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 370.9+ KB


In [12]:
# checking if there are missing values in the Test dataset
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10546 entries, 0 to 10545
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   message  10546 non-null  object
 1   tweetid  10546 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 164.9+ KB


We can observe that both the train and the test datasets are devoid of nulls.

### 2.2.3 Prepare a function for Parts of Speech for modelling

A Part-of-speech (POS) in ML modeling is a grammatical classification that commonly includes verbs ("v"), adjectives ("a"), adverbs("r"), nouns("n"), etc. POS tagging is an important natural language processing application used in machine translation, word sense disambiguation, question answering parsing, and so on. In the cell below, we write a function that extracts the parts of speech from a parsed entry.

In [13]:
def POS(word):
    """
    This function gets the part of speech
    """
    pos_counts = Counter()
    probable_part_of_speech = wordnet.synsets(word)
    pos_counts["n"] = len([i for i in probable_part_of_speech if i.pos()=="n"])
    pos_counts["v"] = len([i for i in probable_part_of_speech if i.pos()=="v"])
    pos_counts["a"] = len([i for i in probable_part_of_speech if i.pos()=="a"])
    pos_counts["r"] = len([i for i in probable_part_of_speech if i.pos()=="r"])
    part_of_speech = pos_counts.most_common(1)[0][0]
    return part_of_speech

### 2.2.4 Extract useful data

The function below will generate new features from the dataset that will be useful in revealing more insights from the data. The function will also extract hashtags from the "message" column and place them in a new column called "hashtags". It will also extract mentions (where the tweet contains @mentions) and place them in a column called "mentions" and lastly, it will extract URLs where they are referenced and place them in a column called "url".

In [14]:
def extractor(df):
    """" 
        Returns a DataFrame with three additional columns: 
        "hashtags", "mentions" and "url"
         Args:
             DataFrame: DateFrame with Data,Index and Colums
        Return:
             DataFrame: A DataFrame with additional columns with data
        Egs:
             df['new colum'] = col_name
    """
    # extract hashtags
    tweets = df['message'] 
    df['hashtags'] = df.message.str.lower().str.findall(r'#.*?(?=\s|$)') 
    htags = df['hashtags']
    df['hashtags'] = htags.apply(lambda x: np.nan if len(x) == 0 else x)
    
    # extract mentions
    df['mentions'] = df.message.str.lower().str.findall(r'@\w*')
    mtags = df['mentions']
    df['mentions'] = mtags.apply(lambda x: np.nan if len(x) == 0 else x)
    
    # extract url
    df['url'] = df.message. str.lower().str.findall(r'http\S+|www.\S+')
    urltags = df['url']
    df['url'] = urltags.apply(lambda x: np.nan if len(x) == 0 else x)
    
    return df


In [16]:
# testing the function
extractor(train_df).head()

sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221   
1          1  It's not like we lack evidence of anthropogeni...   126103   
2          2  RT @RawStory: Researchers say we have three ye...   698562   
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954   

           hashtags            mentions  \
0               NaN         [@mashable]   
1               NaN                 NaN   
2               NaN         [@rawstory]   
3  [#todayinmaker#]                 NaN   
4  [#electionnight]  [@soynoviodetodas]   

                                               url  
0                        [https://t.co/yelvcefxkc]  
1                                              NaN  
2  [https://t.co/wdt0kdur2f, https://t.co/z0anpt…]  
3                        [https://t.co/44wotxtlcd]  
4                                              NaN

In [17]:
# checking the transformation
train_df.head()

sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221   
1          1  It's not like we lack evidence of anthropogeni...   126103   
2          2  RT @RawStory: Researchers say we have three ye...   698562   
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954   

           hashtags            mentions  \
0               NaN         [@mashable]   
1               NaN                 NaN   
2               NaN         [@rawstory]   
3  [#todayinmaker#]                 NaN   
4  [#electionnight]  [@soynoviodetodas]   

                                               url  
0                        [https://t.co/yelvcefxkc]  
1                                              NaN  
2  [https://t.co/wdt0kdur2f, https://t.co/z0anpt…]  
3                        [https://t.co/44wotxtlcd]  
4                                              NaN

### 2.2.5 Removing unnecessary information from the message
Regular expression contains a series of characters that define a pattern of text to be matched to create filters for raw data that may be specialized, or general. Below, we shall use regex codes to clean the data. Recall that we have extracted the URL, mentions, and hashtag information from the original message column to form new columns of their own. We can now remove the information from the message column.

In [19]:
# remove URLs
train_df['message'] = train['message'].str.replace('http\S+|www.\S+', '', case=False)

# remove mentions
train_df['message'] = train['message'].str.replace('@\w*', '', case=False)

# remove hashtags
train_df['message'] = train['message'].str.replace('#.*?(?=\s|$)', '', case=False)

# remove 'RT'
train_df['message'] = train['message'].str.replace('RT :', '', case=False)

# viewing the data
train_df.head()

C:\Users\Buhari Shehu\AppData\Local\Temp\ipykernel_7084\210805835.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  train_df['message'] = train['message'].str.replace('http\S+|www.\S+', '', case=False)
C:\Users\Buhari Shehu\AppData\Local\Temp\ipykernel_7084\210805835.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  train_df['message'] = train['message'].str.replace('@\w*', '', case=False)
C:\Users\Buhari Shehu\AppData\Local\Temp\ipykernel_7084\210805835.py:8: FutureWarning: The default value of regex will change from True to False in a future version.
  train_df['message'] = train['message'].str.replace('#.*?(?=\s|$)', '', case=False)


sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221   
1          1  It's not like we lack evidence of anthropogeni...   126103   
2          2   Researchers say we have three years to act on...   698562   
3          1   WIRED : 2016 was a pivotal year in the war on...   573736   
4          1   It's 2016, and a racist, sexist, climate chan...   466954   

           hashtags            mentions  \
0               NaN         [@mashable]   
1               NaN                 NaN   
2               NaN         [@rawstory]   
3  [#todayinmaker#]                 NaN   
4  [#electionnight]  [@soynoviodetodas]   

                                               url  
0                        [https://t.co/yelvcefxkc]  
1                                              NaN  
2  [https://t.co/wdt0kdur2f, https://t.co/z0anpt…]  
3                        [https://t.co/44wotxtlcd]  
4                                              NaN

### 2.2.6 Expand contractions
Contractions are words or combinations of words that are shortened by dropping letters and replacing them with an apostrophe. Expanding contractions contribute to text standardization and are useful when we are working on Twitter data as the words play an important role in sentiment analysis. The following code string expands the message from the form containing contractions to the expanded form without the contractions.

In [21]:
train_df['message'] = train_df['message'].apply(lambda x: contractions.fix(x))

### 2.2.7 Tokenization
Tokenization is the process of dividing text into a set of meaningful pieces called tokens. To further process the data, we shall build a function that will tokenize the data. The function will also clean the data by removing digits and single character tokens which may contribute nothing to text our interpretation efforts.

In [22]:
def clean_tweets(df):
    '''
    This function cleans the tweets by tokenizing, removing punctuation, 
    removing digits and removing 1 character tokens
    
    '''

    # tokenizing the tweets
    clean_tweets = df['message'].apply(TweetTokenizer().tokenize) ## first we tokenize

    # remove punctuation
    clean_tweets = clean_tweets.apply(lambda x : [token for token in x if token not in string.punctuation])

    # removing digits from the tweets
    clean_tweets = clean_tweets.apply(lambda x: [token for token in x if token not in list(string.digits)])

    # lastly we remove all one character tokens
    clean_tweets = clean_tweets.apply(lambda x: [token for token in x if len(token) > 1])
    
    df['cleaned_tweets'] = clean_tweets
    
    return df['cleaned_tweets']

In [23]:
# input train data in 'clean_tweets' function to clean the tweets
clean_tweets(train_df)

0        [PolySciMajor, EPA, chief, does, not, think, c...
1        [It, is, not, like, we, lack, evidence, of, an...
2        [Researchers, say, we, have, three, years, to,...
3        [WIRED, 2016, was, pivotal, year, in, the, war...
4        [It, is, 2016, and, racist, sexist, climate, c...
                               ...                        
15814    [They, took, down, the, material, on, global, ...
15815    [How, climate, change, could, be, breaking, up...
15816    [notiven, RT, nytimesworld, What, does, Trump,...
15817    [Hey, liberals, the, climate, change, crap, is...
15818         [climate, change, equation, in, screenshots]
Name: cleaned_tweets, Length: 15819, dtype: object

### 2.2.8 Removing Stopwords
Stop words are used in Text Mining and Natural Language Processing (NLP) to eliminate words that are so commonly used that they carry very little useful information for machine algorithms. For example, in the context of a search system, if your search query is “what is a stop word?”, you want the search system to focus on surfacing documents that talk about "stop word" over documents that talk about "what is a".The following code block defines the library to be used for stop word removal. It also removes the stop words from the train dataset. 

In [24]:
# specify the stopword library to be used
stop = stopwords.words('english')

# convert to lower case
train_df['cleaned_tweets'] = train_df['cleaned_tweets'].apply(lambda x: [word.lower() for word in x])

# remove stopwords
train_df['no_stopwords'] = train_df['cleaned_tweets'].apply(lambda x: [item for item in x if item not in stop])

# print out the resulting dataframe
train_df.head()

sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief does not think carbon d...   625221   
1          1  It is not like we lack evidence of anthropogen...   126103   
2          2   Researchers say we have three years to act on...   698562   
3          1   WIRED : 2016 was a pivotal year in the war on...   573736   
4          1   It is 2016, and a racist, sexist, climate cha...   466954   

           hashtags            mentions  \
0               NaN         [@mashable]   
1               NaN                 NaN   
2               NaN         [@rawstory]   
3  [#todayinmaker#]                 NaN   
4  [#electionnight]  [@soynoviodetodas]   

                                               url  \
0                        [https://t.co/yelvcefxkc]   
1                                              NaN   
2  [https://t.co/wdt0kdur2f, https://t.co/z0anpt…]   
3                        [https://t.co/44wotxtlcd]   
4                                              NaN   

                                      cleaned_tweets  \
0  [polyscimajor, epa, chief, does, not, think, c...   
1  [it, is, not, like, we, lack, evidence, of, an...   
2  [researchers, say, we, have, three, years, to,...   
3  [wired, 2016, was, pivotal, year, in, the, war...   
4  [it, is, 2016, and, racist, sexist, climate, c...   

                                        no_stopwords  
0  [polyscimajor, epa, chief, think, carbon, diox...  
1  [like, lack, evidence, anthropogenic, global, ...  
2  [researchers, say, three, years, act, climate,...  
3  [wired, 2016, pivotal, year, war, climate, cha...  
4  [2016, racist, sexist, climate, change, denyin...

### 2.2.9 Most Frequent Words
It would be great to know the words that are most frequently used in the tweet data. This information will provide insight into the topics that are popular among the population from which the data was sourced. The following code block outputs words and the frequency of their occurrence in the tweets. The words are arranged in descending order of frequency (from the most frequently occurring to the least frequently occurring). 


In [26]:
# view a collection of words in the clean data
cnt = Counter()
for message in train_df['no_stopwords'].values:
    for word in message:
        cnt[word] += 1
        
cnt.most_common()

[('climate', 12643),
 ('change', 12577),
 ('global', 3782),
 ('warming', 3519),
 ('trump', 1960),
 ('believe', 1158),
 ('us', 809),
 ('...', 809),
 ('going', 733),
 ('real', 718),
 ('people', 655),
 ('world', 655),
 ('new', 542),
 ('via', 539),
 ('epa', 536),
 ('fight', 474),
 ('like', 470),
 ('says', 430),
 ('science', 424),
 ('die', 420),
 ('scientists', 414),
 ('hoax', 394),
 ('donald', 389),
 ('say', 370),
 ('think', 364),
 ('thinking', 354),
 ('would', 349),
 ('president', 339),
 ("trump's", 322),
 ('husband', 317),
 ('could', 316),
 ('need', 300),
 ('know', 292),
 ('one', 286),
 ('china', 283),
 ('action', 281),
 ('right', 273),
 ('make', 269),
 ('years', 253),
 ('thinks', 250),
 ('stop', 249),
 ('want', 246),
 ('pruitt', 243),
 ('energy', 241),
 ('news', 240),
 ('still', 229),
 ('weather', 227),
 ('must', 223),
 ('due', 220),
 ('time', 218),
 ('earth', 218),
 ('chinese', 216),
 ('planet', 214),
 ('president-elect', 213),
 ('get', 212),
 ('scott', 212),
 ('denier', 208),
 ('good'

### 2.2.10 Map the sentiment classes to their names
Machine learning models work with numeric data but the sentiment values are provided as strings. The following code block maps these strings into numeric form by assigning each string a numeric value. For the purpose of this project, We shall assign the sentiment values as follows. Negative sentiment or "Anti" = -1, "Neutral" = 0, Positive Sentiment or "Pro" = 1, and "News" = 2.

In [27]:
# map the sentiment classes and assign them to numeric values
train_df['sent_labels']  = train_df['sentiment'].map({-1: 'Anti',0:'Neutral', 1:'Pro', 2:'News'})

### 2.2.11 Create separate data frames for each sentiment category
Since we have four distinct categories of sentiments, we will create a separate data frame for each category. This will afford us the flexibility to interact with each sentiment class as a unique entity during the EDA process.

In [29]:
# dataframe for neutral tweets
neutral_df = train_df[train_df['sentiment'] == 0]
# dataframe for pro tweets
pro_df = train_df[train_df['sentiment'] == 1]
# dataframe for anti tweets
anti_df = train_df[train_df['sentiment'] == -1]

The new datframes

In [31]:
neutral_df.head()

sentiment                                            message  tweetid  \
19          0  Calum: *tweets about reunitingish w the cast*\...   547924   
22          0  we also met this guy, he let us in on some tru...    67545   
30          0   are these the same scientists that denounce c...   365051   
39          0  We’ ve dealt with simple issues like climate c...   403368   
43          0   Win probability is bullshit man. I saw the NB...   326916   

    hashtags        mentions                        url  \
19       NaN             NaN                        NaN   
22       NaN             NaN  [https://t.co/q7yomcmzaj]   
30       NaN      [@jnp_ftw]                        NaN   
39  [#qanda]             NaN                        NaN   
43       NaN  [@andrewsharp]                        NaN   

                                       cleaned_tweets  \
19  [calum, tweets, about, reunitingish, the, cast...   
22  [we, also, met, this, guy, he, let, us, in, on...   
30  [are, these, the, same, scientists, that, deno...   
39  [we, ve, dealt, with, simple, issues, like, cl...   
43  [win, probability, is, bullshit, man, saw, the...   

                                         no_stopwords sent_labels  
19  [calum, tweets, reunitingish, cast, sees, repl...     Neutral  
22  [also, met, guy, let, us, truth, climate, chan...     Neutral  
30    [scientists, denounce, climate, change, choice]     Neutral  
39  [dealt, simple, issues, like, climate, change,...     Neutral  
43  [win, probability, bullshit, man, saw, nba, fi...     Neutral

In [32]:
pro_df.head()

sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief does not think carbon d...   625221   
1          1  It is not like we lack evidence of anthropogen...   126103   
3          1   WIRED : 2016 was a pivotal year in the war on...   573736   
4          1   It is 2016, and a racist, sexist, climate cha...   466954   
5          1  Worth a read whether you do or do not believe ...   425577   

           hashtags            mentions  \
0               NaN         [@mashable]   
1               NaN                 NaN   
3  [#todayinmaker#]                 NaN   
4  [#electionnight]  [@soynoviodetodas]   
5               NaN                 NaN   

                                                 url  \
0                          [https://t.co/yelvcefxkc]   
1                                                NaN   
3                          [https://t.co/44wotxtlcd]   
4                                                NaN   
5  [https://t.co/gglzvnyjun, https://t.co/7afe2ma...   

                                      cleaned_tweets  \
0  [polyscimajor, epa, chief, does, not, think, c...   
1  [it, is, not, like, we, lack, evidence, of, an...   
3  [wired, 2016, was, pivotal, year, in, the, war...   
4  [it, is, 2016, and, racist, sexist, climate, c...   
5  [worth, read, whether, you, do, or, do, not, b...   

                                        no_stopwords sent_labels  
0  [polyscimajor, epa, chief, think, carbon, diox...         Pro  
1  [like, lack, evidence, anthropogenic, global, ...         Pro  
3  [wired, 2016, pivotal, year, war, climate, cha...         Pro  
4  [2016, racist, sexist, climate, change, denyin...         Pro  
5   [worth, read, whether, believe, climate, change]         Pro

In [33]:
anti_df.head()

sentiment                                            message  tweetid  \
28         -1  Sally Kohn’s latest evidence of climate change...   355491   
46         -1   Carbon Tax is a Globalist idea to enslave the...    61141   
48         -1   We had winds close to 100 MPH in the area thi...   719523   
56         -1   lmao 😂 snowflakes ❄️ complaining about snowfl...   911385   
57         -1   This is ONE of Arnold Schwarzenegger's vehicl...   768263   

   hashtags            mentions                        url  \
28      NaN      [@twitchyteam]  [https://t.co/mhkzogl9vt]   
46      NaN  [@realdonaldtrump]                        NaN   
48      NaN    [@stevesgoddard]                        NaN   
56      NaN      [@misslizzynj]                        NaN   
57      NaN     [@dawn2334dawn]                    [http…]   

                                       cleaned_tweets  \
28  [sally, kohn, latest, evidence, of, climate, c...   
46  [carbon, tax, is, globalist, idea, to, enslave...   
48  [we, had, winds, close, to, 100, mph, in, the,...   
56  [lmao, snowflakes, complaining, about, snowfla...   
57  [this, is, one, of, arnold, schwarzenegger's, ...   

                                         no_stopwords sent_labels  
28  [sally, kohn, latest, evidence, climate, chang...        Anti  
46  [carbon, tax, globalist, idea, enslave, world'...        Anti  
48  [winds, close, 100, mph, area, afternoon, woul...        Anti  
56  [lmao, snowflakes, complaining, snowflakes, wi...        Anti  
57  [one, arnold, schwarzenegger's, vehicles, whin...        Anti

 ### 2.2.12 Exploratory Data Analysis

In this sub-section we want to apply a variety of techniques to maximize specific insights into our dataset, reveal underlying structure, extract significant variables, detect outliers and anomalies, test assumptions, develop models, and determine the best parameters for estimations. In essence, we want to dig deeper into our dataset to gain more insights into its nature and draw conclusions based on what we learn from the data.

**Target variable**
We want to understand the behavior of our target variable for our respective categories. The following code block iterates through the target variables as contained in the train set and identifies the percentage of the target that falls into each sentiment category (That is the percentage contribution of each sentiment category to the overall sentiment of the set). From the information displayed, we can see that the Pro category contributes the most with 54%, it is followed by the News category with 23% and then Neutral with 15% and lastly Anti with 8%.

<a id="three"></a>
# 3.0 Model Building and Evaluations
In this section, we are going to build and evalaute various ML models and select the best one amongst them. Will attempt improving the performance of our models by hyper parameter tuning and we will evaluate the performance of these in our dataset:
- Naive Bayes Classifier
- SVC and LinearSVC
- Logistic Regression
- KNN
- Decision Tree
- Random Forests

<a id="3.1"></a>
## 3.1 Train-test Split
After we create a function for preprocessing we must split the data into labels and features (X and y) in order to enable us the run the models on our data sets.

In [26]:
# Splitting the labels and features
train['processed'] = train['message'].apply(tweet_preprocessing)
X = train['processed'].values
y = train['sentiment'].values

time: 1.05 s (started: 2022-06-21 14:49:24 +01:00)


In [27]:
# preprocess testing data by applying our function
test['processed'] = test['message'].apply(tweet_preprocessing)

time: 641 ms (started: 2022-06-21 14:49:25 +01:00)


<a id="3.2"></a>
## 3.2 Feature Selection

<a id="3.3"></a>
## 3.3 Model Building

### a. Naive Bayes Classifier 

In [28]:
# Splitting the labels and fetures into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10,random_state=42,stratify=y)

time: 218 ms (started: 2022-06-21 14:50:34 +01:00)


In [ ]:
mnb = Pipeline([('Count',CountVectorizer()),('classify',MultinomialNB())])
#fitting the model
mnb.fit(X_train, y_train)

#apply model on test data
y_pred_mnb = mnb.predict(X_test)

In [ ]:
# Classification report
print(classification_report(y_test, y_pred_mnb))

As we can see the '-1' and '0' class are poorly predicted when using unbalanced data. Once we implement resampling their f1-score increases for these model but only slightly. While at the same time the overall accuracy is slightly reduced.

### b. SVC and LinearSVC

SVC Provides a best fit to catergorize our data this fit can be nonlinear, while a linearSVC provides a linear interpolation.

In [ ]:
#SVC
svc = Pipeline([('Count',CountVectorizer()),('classify',SVC(max_iter=300,C=1))])

In [ ]:
#linearSVC
linsvc = Pipeline([('Count',CountVectorizer()),('classify',LinearSVC(max_iter=300,C=1))])

### c. Logistic Regression

Models the discrete probability distribution between classes and classifies based on the inflection point of the curve.

In [ ]:
#Logistic Regression
lr = Pipeline([('Count',CountVectorizer()),('classify',LogisticRegression(max_iter=300))])

### d. KNN
The KNN classifier assumes that all data points that similar data points tend to form clusters, close together. It classifies points that are close into the same class.K is the number of neighbours. So K=3 implies we will make our predictions based off of the 3 closest points to the data point beign assessed.

In [ ]:
# Invoke the KNN classifier
knn = Pipeline([('Count',CountVectorizer()),('classify',KNeighborsClassifier(n_neighbors=3))])

### e. Decision Tree

The decision tree uses a tree-like model of decisions and their possible consequences.Starting from the decision itself (called a "node"), each branch of the decision tree represents a possible decision, outcome, or reaction and it works up until there is only one possible outcome left.
<div align="center" style="width: 500px; font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://www.aihr.com/wp-content/uploads/decision-trees-in-analytics.png"
     alt="Dummy image 1"
     style="float: center; padding-bottom=0.5em"
     width=500px/>

In [ ]:
#Decision Tree
dt = Pipeline([('Count',CountVectorizer()),('classify',DecisionTreeClassifier())])

### f. Random Forest
Using the decision tree as a base estimator,each estimator is trained on a different bootstrap sample having the same size as the training set. At each node of the forest, features are sampled without replacement to increase randomization. Nodes are split to maximise information gain.   

<div align="center" style="width: 500px; font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://cdn.analyticsvidhya.com/wp-content/uploads/2020/05/rfc_vs_dt11.png"
     alt="Dummy image 1"
     style="float: center; padding-bottom=0.5em"
     width=500px/>

In [ ]:
# Call up the Random Forest Sampler
rf = Pipeline([('Count',CountVectorizer()),('classify',RandomForestClassifier())])

<a id="3.4"></a>
### 3.4 Model Evaluation and Performance

In [32]:
num=3
# SVC
scores = cross_val_score(
        svc, X, y, cv=num, scoring='f1_weighted')
print('The average weighted F1 score over '+str(num)+' SVC models is ' + str(sum(scores)/len(scores)))

NameError: name 'svc' is not defined

time: 156 ms (started: 2022-06-21 15:27:09 +01:00)


In [ ]:
#linearSVC
scores = cross_val_score(
        linsvc, X, y, cv=num, scoring='f1_weighted')
print('The average weighted F1 score over '+str(num)+ ' LinearSVC models is ' + str(sum(scores)/len(scores)))

In [ ]:
#Logistic Regression
scores = cross_val_score(
        lr, X, y, cv=num, scoring='f1_weighted')
print('The average weighted F1 score over '+str(num)+' Logistic Regression models is ' + str(sum(scores)/len(scores)))

In [ ]:
#KNN
scores = cross_val_score(
        knn, X, y, cv=num, scoring='f1_weighted')
print('The average weighted F1 score over '+str(num)+' KNN models is ' + str(sum(scores)/len(scores)))

In [ ]:
#Decision Tree
scores = cross_val_score(
        dt, X, y, cv=num, scoring='f1_weighted')
print('The average weighted F1 score over '+str(num)+' Decision Tree models is ' + str(sum(scores)/len(scores)))

In [ ]:
#Random Forest
scores = cross_val_score(
        rf, X, y, cv=num, scoring='f1_weighted')
print('The average weighted F1 score over '+str(num)+' KNN models is ' + str(sum(scores)/len(scores)))

The Logistic Regression Model and the LinearSVC model perform the best. The best performance for every model is found when resampling is not done. This could be because because upsampling the minority classes to the level of the majority class results in too much overfitting.

<a id="3.5"></a>
### 3.5 Parameter Tunings

We take a look and see if we can improve our best 2 models: linearSVC and Logistic Regression

In [ ]:
from sklearn.model_selection import GridSearchCV
Cs = [0.001, 0.01, 0.1, 1, 10]
param_grid = {
    'C'     : Cs
    }
grid_SVM = GridSearchCV(LogisticRegression(), param_grid, scoring='f1_weighted', cv=3)
grid_SVM.fit(CountVectorizer().fit_transform(X), y)
grid_SVM.best_params_

In [ ]:
param_grid = {'C'     : Cs }
grid_SVM = GridSearchCV(LinearSVC(), param_grid, scoring='f1_weighted', cv=3)
grid_SVM.fit(CountVectorizer().fit_transform(X), y)
grid_SVM.best_params_

<a id="four"></a>
# 4.0 Conclusion

### Model performance
Several strategies we attempted to improve model performance, ranging from data processing techniques to clean the tweets, data balancing strategies, cross validation and grid search for the best values for model hyperparameters.



### What else we can try
Language models and the use of neural networks were two other strategies that we may implement to see how it will compare with essemble tree based models. It will also provide an opportunity for us to see how neural network models perforn on Natural Language tasks.

### Business case value

The analysis shows generally that the sentiment from the negative tweets arise from a a class of people who believe that climate change and the incidence of global warming is a hoax, or at best overated. Most of these persons defend their ideology with strong resolve and it will therefore be counter productive to try to market environmentally friendly products to them as an effort towards sustainability or to combat the incidence of Climate change. This class are more likely to become customers if other aspects of the product is promoted to them. They are more likely to purchase a product because of quality, fairness in price, use case etc rather than just because it is sustainably produced or good for the environmenmt.

Conversely, People from the other end of the spectrum who display positive sentiments towards climate change definitely believe that climate change is an issue. They show some willingness to "do something" to play their role in combating this issue. What is yet unclear is if their sentiments would translate to any meaningful influence on their product aquisition habbits. They are definitely a better group to target with promotions that highlights the sustainability and environmenmtal friendliness of the products. To be safe though, this message should be embedded in other qualities of the product so that the environmental friendliness would be the Icing on the cake. It would be great for them if they have a product which is good already but also is sustainably produced. 


It will be beneficial for companies or organizations to band together and form groups where Some organisations are mentioned in the tweets, many which share the same values and ideals when it comes to protecting the environment, who have a substantial membership and following on social media of individuals who share the same values and ideals. The formation of potential partnerships with these organisations could lead to brand exposure with individuals who in their daily lives make conscious decisions with regards to the products and services they purchase.

We recommend that the latter strategy of pursuing partnerships with like minded organisations will yield the best results, in terms of finding a group of potential customers who share the same values and ideals, and would be likely to purchase your products and services.

<a id="five"></a>
# Submission

For our final model, we build a stacking classifier to combine Logistic Regression, LinearSVC and Random Forest

In [ ]:
estimators = [
       ('rf', Pipeline([('Count',CountVectorizer(ngram_range=(1,2))),('classify',RandomForestClassifier())])),
         
        ('lnsvc', Pipeline([('Count',CountVectorizer(ngram_range=(1,2))),('classify',LinearSVC(C=0.1))])),
         
        ('MNB',Pipeline([('Count',CountVectorizer()),('classify',MultinomialNB())])),
    
        ('lr', Pipeline([('Count',CountVectorizer(ngram_range=(1,2))),('classify',LogisticRegression(C=1))]))]

In [ ]:
clf = StackingClassifier(
        estimators=estimators
    )

#fitting the model
clf.fit(X, y)

In [ ]:
# End experiment
experiment.end()

In [ ]:
# Display results on comet page
experiment.display()

In [ ]:
# Creating the unseen set, so that we can post to Kaggle and recieve a score based on the performance
x_unseen = test['processed']

submission = pd.DataFrame(
    {'tweetid': test['tweetid'],
     'sentiment': clf.predict(x_unseen)
    })

# save DataFrame to csv file for submission
submission.to_csv("Submission_final.csv", index=False)

# References

<div align="center" style="color: white, background:#000099">
    <b>Copyright &copy 2022 Datafluent Inc.</b>
</div>